server:
  port: 8080
spring:
  cloud:
    config:
      server: 
        git:
          default-label: eureka-server
          uri: https://github.com/bzavalavaldivia/java-microservices
          search-paths: config-data
  application:
    name: ms-config